set lang en
	
mcset $lang \
	{year} \
	{year}

mcset $lang \
	{years} \
	{years}

mcset $lang \
	{month} \
	{month}

mcset $lang \
	{months} \
	{months}

mcset $lang \
	{week} \
	{week}

mcset $lang \
	{weeks} \
	{weeks}

mcset $lang \
	{day} \
	{day}

mcset $lang \
	{days} \
	{days}

mcset $lang \
	{hour} \
	{hour}

mcset $lang \
	{hours} \
	{hours}

mcset $lang \
	{minute} \
	{minute}

mcset $lang \
	{minutes} \
	{minutes}

mcset $lang \
	{second} \
	{second}

mcset $lang \
	{seconds} \
	{seconds}

mcset $lang \
	{%1$s was last seen %2$s ago.} \
	{%1$s was last seen %2$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen parting a channel %3$s ago.} \
	{%1$s (%2$s) was last seen parting a channel %3$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen parting %3$s %4$s ago.} \
	{%1$s (%2$s) was last seen parting %3$s %4$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen parting a channel %3$s ago, stating "%4$s"} \
	{%1$s (%2$s) was last seen parting a channel %3$s ago, stating "%4$s"}

mcset $lang \
	{%1$s (%2$s) was last seen parting %3$s %4$s ago, stating "%5$s"} \
	{%1$s (%2$s) was last seen parting %3$s %4$s ago, stating "%5$s"}

mcset $lang \
	{%1$s (%2$s) was last seen joining a channel %3$s ago.} \
	{%1$s (%2$s) was last seen joining a channel %3$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen joining %3$s %4$s ago. %5$s is still on %1$s.} \
	{%1$s (%2$s) was last seen joining %3$s %4$s ago. %5$s is still on %1$s.}

mcset $lang \
	{%1$s (%2$s) was last seen joining %3$s %4$s ago. I don't see %1$s on %3$s now, though.} \
	{%1$s (%2$s) was last seen joining %3$s %4$s ago. I don't see %1$s on %3$s now, though.}

mcset $lang \
	{%1$s (%2$s) was last seen changing nicks to %4$s on a channel %3$s ago.} \
	{%1$s (%2$s) was last seen changing nicks to %4$s on a channel %3$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen changing nicks to %5$s on %3$s %4$s ago.} \
	{%1$s (%2$s) was last seen changing nicks to %5$s on %3$s %4$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen changing nicks from %4$s on a channel %3$s ago.} \
	{%1$s (%2$s) was last seen changing nicks from %4$s on a channel %3$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen changing nicks from %5$s on %3$s %4$s ago. %1$s is still on %3$s.} \
	{%1$s (%2$s) was last seen changing nicks from %5$s on %3$s %4$s ago. %1$s is still on %3$s.}

mcset $lang \
	{%1$s (%2$s) was last seen changing nicks from %5$s on %3$s %4$s ago. I don't see %1$s on %3$s now, though.} \
	{%1$s (%2$s) was last seen changing nicks from %5$s on %3$s %4$s ago. I don't see %1$s on %3$s now, though.}

mcset $lang \
	{%1$s (%2$s) was last seen quitting from a channel %3$s ago.} \
	{%1$s (%2$s) was last seen quitting from a channel %3$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen quitting from %3$s %4$s ago.} \
	{%1$s (%2$s) was last seen quitting from %3$s %4$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen quitting from %3$s %4$s ago, stating "%5$s"} \
	{%1$s (%2$s) was last seen quitting from %3$s %4$s ago, stating "%5$s"}

mcset $lang \
	{%1$s (%2$s) was last seen parting a channel due to a netsplit %3$s ago.} \
	{%1$s (%2$s) was last seen parting a channel due to a netsplit %3$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen parting %3$s due to a netsplit %4$s ago.} \
	{%1$s (%2$s) was last seen parting %3$s due to a netsplit %4$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen rejoining a channel from a netsplit %3$s ago.} \
	{%1$s (%2$s) was last seen rejoining a channel from a netsplit %3$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen rejoining %3$s from a netsplit %4$s ago. %1$s is still on %3$s.} \
	{%1$s (%2$s) was last seen rejoining %3$s from a netsplit %4$s ago. %1$s is still on %3$s.}

mcset $lang \
	{%1$s (%2$s) was last seen kicked from a channel %3$s ago.} \
	{%1$s (%2$s) was last seen kicked from a channel %3$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen kicked from %3$s by %4$s %5$s ago, with the reason "%6$s"} \
	{%1$s (%2$s) was last seen kicked from %3$s by %4$s %5$s ago, with the reason "%6$s"}

mcset $lang \
	{%1$s (%2$s) was last seen entering the partyline %3$s ago. %1$s is on the partyline right now.} \
	{%1$s (%2$s) was last seen entering the partyline %3$s ago. %1$s is on the partyline right now.}

mcset $lang \
	{%1$s (%2$s) was last seen entering the partyline %3$s ago. I don't see %1$s on the partyline now, though.} \
	{%1$s (%2$s) was last seen entering the partyline %3$s ago. I don't see %1$s on the partyline now, though.}

mcset $lang \
	{%1$s (%2$s) was last seen leaving the partyline %3$s ago. %1$s is on the partyline channel %4$s still.} \
	{%1$s (%2$s) was last seen leaving the partyline %3$s ago. %1$s is on the partyline channel %4$s still.}

mcset $lang \
	{%1$s (%2$s) was last seen leaving the partyline %3$s ago.} \
	{%1$s (%2$s) was last seen leaving the partyline %3$s ago.}

mcset $lang \
	{%1$s (%2$s) was last seen entering the partyline on %3$s %4$s ago. %1 is on the partyline right now.} \
	{%1$s (%2$s) was last seen entering the partyline on %3$s %4$s ago. %1 is on the partyline right now.}

mcset $lang \
	{%1$s (%2$s) was last seen entering the partyline on %3$s %4$s ago. I don't see %1$s on the partyline now, though.} \
	{%1$s (%2$s) was last seen entering the partyline on %3$s %4$s ago. I don't see %1$s on the partyline now, though.}

mcset $lang \
	{%1$s (%2$s) was last seen leaving the partyline from %3$s %4$s ago. %1$s is on the partyline channel %5$s still.} \
	{%1$s (%2$s) was last seen leaving the partyline from %3$s %4$s ago. %1$s is on the partyline channel %5$s still.}

mcset $lang \
	{%1$s (%2$s) was last seen leaving the partyline from %3$s %4$s ago.} \
	{%1$s (%2$s) was last seen leaving the partyline from %3$s %4$s ago.}

mcset $lang \
	{%1$s was last seen marked as away (%2$s) on the partyline %3$s ago. %1$s is on the partyline right now.} \
	{%1$s was last seen marked as away (%2$s) on the partyline %3$s ago. %1$s is on the partyline right now.}

mcset $lang \
	{%1$s was last seen marked as away (%2$s) on the partyline %3$s ago. I don't see %1$s on the partyline now, though.} \
	{%1$s was last seen marked as away (%2$s) on the partyline %3$s ago. I don't see %1$s on the partyline now, though.}

mcset $lang \
	{%1$s was last seen returning to the partyline %2$s ago. %1$s is on the partyline right now.} \
	{%1$s was last seen returning to the partyline %2$s ago. %1$s is on the partyline right now.}

mcset $lang \
	{%1$s was last seen returning to the partyline %2$s ago. I don't see %1$s on the partyline now, though.} \
	{%1$s was last seen returning to the partyline %2$s ago. I don't see %1$s on the partyline now, though.}

mcset $lang \
	{I don't remember seeing %s.} \
	{I don't remember seeing %s.}

mcset $lang \
	{%s, that is not a valid nickname.} \
	{%s, that is not a valid nickname.}

mcset $lang \
	{%s, go look in a mirror.} \
	{%s, go look in a mirror.}

mcset $lang \
	{You found me, %s!} \
	{You found me, %s!}

mcset $lang \
	{%s is on the channel right now!} \
	{%s is on the channel right now!}

mcset $lang \
	{%1$s is on the channel right now! %1$s last spoke %2$s ago.} \
	{%1$s is on the channel right now! %1$s last spoke %2$s ago.}

mcset $lang \
	{That is not a valid nickname.} \
	{That is not a valid nickname.}

mcset $lang \
	{Go look in a mirror.} \
	{Go look in a mirror.}

mcset $lang \
	{You found me!} \
	{You found me!}
	
mcset $lang \
	{pixseen.tcl: No existing database found, defining SQL schema.} \
	{pixseen.tcl: No existing database found, defining SQL schema.}

mcset $lang \
	{pixseen.tcl: Loaded the seen database.} \
	{pixseen.tcl: Loaded the seen database.}

mcset $lang \
	{pixseen.tcl: Unloaded the seen database.} \
	{pixseen.tcl: Unloaded the seen database.}

mcset $lang \
	{SQL error %1$s; %2$s} \
	{SQL error %1$s; %2$s}

mcset $lang \
	{pixseen.tcl SQL error %1$s; %2$s} \
	{pixseen.tcl SQL error %1$s; %2$s}
	
mcset $lang \
	{pixseen.tcl error; ::pixseen::idx2uhost was unable to extract uhost. PLEASE REPORT THIS BUG!} \
	{pixseen.tcl error; ::pixseen::idx2uhost was unable to extract uhost. PLEASE REPORT THIS BUG!}
	
mcset $lang \
	{pixseen.tcl error; Unhandled event in db_get: %s} \
	{pixseen.tcl error; Unhandled event in db_get: %s}

mcset $lang \
	{pixseen.tcl error; Unhandled event in db_add: %s} \
	{pixseen.tcl error; Unhandled event in db_add: %s}

mcset $lang \
	{Loaded %1$s v%2$s by %3$s} \
	{Loaded %1$s v%2$s by %3$s}
